services:
  - type: web
    name: myapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
  - type: postgresql
    name: mydb
    ipAllowList: []
databases:
  - name: mydb